<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'administratorcategoriescest' => '/acceptance/administrator/AdministratorCategoriesCest.php',
                'administratorweblinkscest' => '/acceptance/administrator/AdministratorWeblinksCest.php',
                'codeception\\module\\acceptancehelper' => '/_support/AcceptanceHelper.php',
                'codeception\\module\\functionalhelper' => '/_support/FunctionalHelper.php',
                'codeception\\module\\unithelper' => '/_support/UnitHelper.php',
                'frontendweblinkscest' => '/acceptance/frontend/FrontendWeblinksCest.php',
                'installweblinkscest' => '/acceptance/install/InstallWeblinksCest.php',
                'step\\acceptance\\weblink' => '/_support/Step/Acceptance/weblink.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
