<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'weblinkscontroller' => '/controller.php',
                'weblinkscontrollerweblink' => '/controllers/weblink.php',
                'weblinkscontrollerweblinks' => '/controllers/weblinks.php',
                'weblinkshelper' => '/helpers/weblinks.php',
                'weblinksmodelweblink' => '/models/weblink.php',
                'weblinksmodelweblinks' => '/models/weblinks.php',
                'weblinkstableweblink' => '/tables/weblink.php',
                'weblinksviewweblink' => '/views/weblink/view.html.php',
                'weblinksviewweblinks' => '/views/weblinks/view.html.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
