<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'jhtmlicon' => '/helpers/icon.php',
                'weblinkscategories' => '/helpers/category.php',
                'weblinkscontroller' => '/controller.php',
                'weblinkscontrollerweblink' => '/controllers/weblink.php',
                'weblinkshelperassociation' => '/helpers/association.php',
                'weblinkshelperroute' => '/helpers/route.php',
                'weblinksmodelcategories' => '/models/categories.php',
                'weblinksmodelcategory' => '/models/category.php',
                'weblinksmodelform' => '/models/form.php',
                'weblinksmodelweblink' => '/models/weblink.php',
                'weblinksrouter' => '/router.php',
                'weblinksviewcategories' => '/views/categories/view.html.php',
                'weblinksviewcategory' => '/views/category/view.html.php',
                'weblinksviewcategoryfeed' => '/views/category/view.feed.php',
                'weblinksviewform' => '/views/form/view.html.php',
                'weblinksviewweblink' => '/views/weblink/view.html.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
